from django.shortcuts import render
from ._views.MenuItems import MenuItemsView
from ._views.CategoryView import CategoryView
from ._views.MasterMenuItemView import MasterMenuItemView
from ._views.MasterMenuCategoryView import MasterMenuCategoryView
from ._views.LocationMenuItemView import LocationMenuItemView
from ._views.LocationCategoryView import LocationCategoryView
from ._views.MasterMenuItemLocationsView import MasterMenuItemLocationsView
from ._views.MenuItemsArchive import MenuItemsArchive
from ._views.CategoryArchiveView import CategoryArchiveView 